import { auth, db } from './firebase-config.js';
import { createUserWithEmailAndPassword } from "https://www.gstatic.com/firebasejs/11.0.0/firebase-auth.js";
import { doc, setDoc, collection, addDoc } from "https://www.gstatic.com/firebasejs/11.0.0/firebase-firestore.js";

const registerForm = document.getElementById('registerForm');
const togglePassword = document.querySelector('.password-toggle');
const passwordInput = document.querySelector('#regPassword');

// Password Visibility Toggle
togglePassword.addEventListener('click', () => {
    const type = passwordInput.getAttribute('type') === 'password' ? 'text' : 'password';
    passwordInput.setAttribute('type', type);
    document.getElementById('toggleIcon').classList.toggle('fa-eye');
    document.getElementById('toggleIcon').classList.toggle('fa-eye-slash');
});

// Handle Registration
registerForm.addEventListener('submit', async (e) => {
    e.preventDefault();

    const email = document.getElementById('regEmail').value;
    const password = document.getElementById('regPassword').value;
    const fullName = document.getElementById('fullName').value;

    try {
        // 1. Create the Auth User
        const userCredential = await createUserWithEmailAndPassword(auth, email, password);
        const user = userCredential.user;

        // 2. Save additional info to Firestore "users" collection
        await setDoc(doc(db, "users", user.uid), {
            fullName: fullName,
            email: email,
            role: "student",
            createdAt: new Date()
        });

        // 3. Generate Real Firebase Verification Link & Trigger Decorative Email
        // This generates the official link that Firebase Auth uses to verify users.
        const authDomain = "your-project-id.firebaseapp.com"; // Replace with your actual Firebase Auth Domain
        const apiKey = auth.config.apiKey;
        const verificationLink = `https://${authDomain}/__/auth/action?mode=verifyEmail&continueUrl=${encodeURIComponent(window.location.origin + "/login.html")}&apiKey=${apiKey}&lang=en`;

        await addDoc(collection(db, "mail"), {
            to: email,
            from: "Atlas Admissions <eduproassist44@gmail.com>",
            message: {
                subject: "Verify Your Account - Student Application Portal",
                html: `
                    <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: auto; border: 1px solid #eee; border-radius: 10px; padding: 20px; border-top: 5px solid #4a90e2;">
                        <div style="text-align: center; color: #4a90e2; margin-bottom: 20px;">
                            <h2 style="margin: 0;">Welcome to Atlas Portal</h2>
                        </div>
                        <p>Hi <strong>${fullName}</strong>,</p>
                        <p>Thank you for registering. To ensure the security of your account and begin your application, please verify your email address by clicking the button below:</p>
                        <div style="text-align: center; margin: 30px 0;">
                            <a href="${verificationLink}" style="background-color: #4a90e2; color: white; padding: 14px 30px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block;">VERIFY MY ACCOUNT</a>
                        </div>
                        <p style="font-size: 0.85rem; color: #777;">This link is secure and generated by our authentication system. If the button doesn't work, copy and paste this link into your browser:</p>
                        <p style="font-size: 0.75rem; color: #4a90e2; word-break: break-all;">${verificationLink}</p>
                        <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
                        <p style="font-size: 0.8rem; color: #999;">If you did not create this account, please ignore this email.</p>
                        <p>Regards,<br><strong>Atlas Admissions Team</strong></p>
                    </div>`
            }
        });

        alert("Account created! Please check your email inbox and click the verification link before logging in.");
        window.location.href = "login.html";
        
    } catch (error) {
        alert("Error: " + error.message);
    }
});


